
language: csharp
solution: NUnit.Web.Tests.sln
before_install:
  - sudo apt-get install nunit3-console
before_script:
  - nuget restore NUnit.Web.Tests.sln
after_script:
  - nunit3-console NUnit.Web.Tests.dll 